// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2J6OIlOXjTAm_SAq9Rkalhy0JeJPtgew',
    appId: '1:763224214668:web:af0b553383a6c2be81bfa9',
    messagingSenderId: '763224214668',
    projectId: 'todoapp-b532b',
    authDomain: 'todoapp-b532b.firebaseapp.com',
    storageBucket: 'todoapp-b532b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5XzIWubd4au9MIr8wBRO6G0BvVYBQnL0',
    appId: '1:763224214668:android:75d6c65236dd455281bfa9',
    messagingSenderId: '763224214668',
    projectId: 'todoapp-b532b',
    storageBucket: 'todoapp-b532b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGxcj6hbUIy3tMCAzCVdXxbPReIO7-fbc',
    appId: '1:763224214668:ios:949abb7aa066e91f81bfa9',
    messagingSenderId: '763224214668',
    projectId: 'todoapp-b532b',
    storageBucket: 'todoapp-b532b.appspot.com',
    iosClientId: '763224214668-348d7b8vksaddvfprf86c974ched23o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNewProjects',
  );
}
